version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - flask_network

  flaskapp:
    build: .
    container_name: flask_container
    restart: always
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - flask_network

volumes:
  mysql_data:

networks:
  flask_network:
    driver: bridge
